novelbot/Backend

src/main/java/com/novelbot/api/controller/EpisodeController.java
src/main/java/com/novelbot/api/domain/Chatroom.java
src/main/java/com/novelbot/api/domain/Episode.java
src/main/java/com/novelbot/api/domain/Novel.java
src/main/java/com/novelbot/api/domain/Purchase.java
src/main/java/com/novelbot/api/domain/Queries.java
src/main/java/com/novelbot/api/domain/QueryEpisode.java
src/main/java/com/novelbot/api/domain/User.java
src/main/java/com/novelbot/api/domain/UserReadingProcess.java
src/main/java/com/novelbot/api/repository/EpisodeRepository.java
src/main/java/com/novelbot/api/service/settingEpisode/EpisodeService.java
src/main/java/com/novelbot/api/utility/ImportEpisode/EpisodeImport.java
src/main/java/com/novelbot/api/utility/ImportNovel/NovelImport.java

Camel Notation에 따른 자바 변수명 수정
---
- api/domain/*과 api/dto/* 변수명 변경
---
---
```bash
close #10

Refactor: java variable name refactor with camel notation

---

src/main/java/com/novelbot/api/domain/Episode.java
src/main/java/com/novelbot/api/domain/User.java
src/main/java/com/novelbot/api/domain/UserReadingProgress.java
src/main/java/com/novelbot/api/dto/auth/LoginRequest.java
src/main/java/com/novelbot/api/dto/chat/ChatroomCreateRequest.java
src/main/java/com/novelbot/api/dto/chat/QueryCreateRequest.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
curl -X POST http://localhost:3000/api/login \
-H 'Content-Type: application/json' \
-d '{"email": "test@example.com", "password": "1234"}'
close #13

[Refactor] 누락된 파일 추가

---

src/main/java/com/novelbot/api/domain/Episode.java
src/main/java/com/novelbot/api/domain/Novel.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
curl -X POST http://localhost:3000/api/login \
-H 'Content-Type: application/json' \
-d '{"email": "test@example.com", "password": "1234"}'
close #13

update 오류 수정

---

src/main/resources/application.properties

server의 환경 변수를 통해 application.properties 구성
---
- application.properties
---
---
- 생략

Fix: application.properties 수정

---

src/main/java/com/novelbot/api/controller/ChatController.java
src/main/java/com/novelbot/api/controller/EpisodeController.java
src/main/java/com/novelbot/api/controller/NovelController.java
src/main/java/com/novelbot/api/controller/PurchaseController.java
src/main/java/com/novelbot/api/controller/ReadingProgressController.java
src/main/java/com/novelbot/api/controller/UserController.java

API 명세의 경로와 요청에 따른 Controller Skeleton 작성
---
예:
- Controller Skeleton 작성으로 반환 타입 구체화
---
---
- 생략
#12

[Feat] Controller Skeleton create

---

README.md
src/main/java/com/novelbot/api/controller/ChatController.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
curl -X POST http://localhost:3000/api/login \
-H 'Content-Type: application/json' \
-d '{"email": "test@example.com", "password": "1234"}'
close #

[Feat] upstream 받기 위한 준비

---

src/main/java/com/novelbot/api/controller/UserController.java
src/main/java/com/novelbot/api/repository/EpisodeRepository.java
src/main/java/com/novelbot/api/repository/NovelRepository.java
src/main/java/com/novelbot/api/repository/ReadingProgressRepository.java
src/main/java/com/novelbot/api/repository/UserRepository.java

Repository 일부 작성
---
예:
- EpisodeRepository 추가
- NovelRepository 추가
- UserRepository 추가
- ReadingProgessRepository 작성 중 (파일 이름을 UserReadingProgressRepository로 수정 예정)
---
---
- 생략
#35

[Feat] Repository 추가

---

build.gradle
src/main/java/com/novelbot/api/config/SecurityConfig.java
src/main/java/com/novelbot/api/domain/User.java
src/main/java/com/novelbot/api/mapper/auth/LoginRequestDtoMapper.java
src/main/java/com/novelbot/api/mapper/user/UserCreateRequestDtoMapper.java
src/main/java/com/novelbot/api/repository/UserRepository.java
src/main/java/com/novelbot/api/service/auth/LoginService.java
src/main/java/com/novelbot/api/service/auth/LogoutService.java
src/main/java/com/novelbot/api/service/auth/RegistrationService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
curl -X POST http://localhost:3000/api/login \
-H 'Content-Type: application/json' \
-d '{"email": "test@example.com", "password": "1234"}'
close #

login, logout ã로직 작성

---

.github/PULL_REQUEST_TEMPLATE.md
build.gradle
src/main/java/com/novelbot/api/controller/AuthController.java
src/main/java/com/novelbot/api/controller/EpisodeController.java
src/main/java/com/novelbot/api/controller/NovelController.java
src/main/java/com/novelbot/api/controller/UserController.java
src/main/resources/application.properties
src/test/java/com/novelbot/api/ApiApplicationTests.java

backend-server deploy 테스트
---
- backend server 배포 가능한 지 테스트
---
---
- github CI test 통과
예:
```bash
./gradlew clean build
./gradlew test
#46

[Deploy] deploy test

---

.github/workflows/deploy.yml

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] github workflow

---

src/main/java/com/novelbot/api/domain/Episode.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] Episode가 NovelId를 외래키로 참조하도록 수정

---

build.gradle
src/main/java/com/novelbot/api/domain/Episode.java
src/main/java/com/novelbot/api/dto/chat/QueryDto.java
src/main/java/com/novelbot/api/mapper/novel/EpisodeDtoMapper.java
src/main/java/com/novelbot/api/mapper/novel/EpisodeListDtoMapper.java
src/main/java/com/novelbot/api/repository/ChatRepository.java
src/main/java/com/novelbot/api/repository/QueryRepository.java

type 불일치로 인한 컴파일 에러 해결
---
예:
- Episode Entity에서 novelId type int로 변경(기존에 Novel type이었음.. 왜지?)
- QueryDTO도 type 변경
---
---
```bash
./gradlew clean build

[Feat] Episode entity, QueryDTO type 변경

---

src/main/java/com/novelbot/api/domain/Chatroom.java
src/main/java/com/novelbot/api/service/chat/ChatroomService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

í채팅방 ìservice 수정

---

src/main/java/com/novelbot/api/domain/Chatroom.java
src/main/java/com/novelbot/api/repository/QueryRepository.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] Chatroom NoargsConstructor 추가, Queries import 수정

---

src/main/java/com/novelbot/api/config/SecurityConfig.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] health check를 위한 보안 검증 제외

---

src/main/java/com/novelbot/api/config/SecurityConfig.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] 모든 권한 허가

---

build.gradle
src/main/resources/application.properties

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] springboot actuator 추가

---

src/main/java/com/novelbot/api/controller/AuthController.java
src/main/java/com/novelbot/api/controller/ChatController.java
src/main/java/com/novelbot/api/controller/EpisodeController.java
src/main/java/com/novelbot/api/controller/QueryController.java
src/main/java/com/novelbot/api/controller/UserController.java
src/main/java/com/novelbot/api/service/novel/EpisodeService.java

- Episode Content 확인 오류 로직 수정
---
- isEmpty()의 경우 404 Not Found 반환
---
---
예:
```bash
close #

[Fix] Episode Content 확인 로직 수정

---

src/main/java/com/novelbot/api/service/chat/ChatroomService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

채팅방 조회 메서드 dto 반환 코드 수정

---

build.gradle
node_modules/.package-lock.json
src/main/java/com/novelbot/api/config/JwtTokenProvider.java
src/main/java/com/novelbot/api/config/JwtTokenValidator.java
src/main/java/com/novelbot/api/config/SecurityConfig.java
src/main/java/com/novelbot/api/domain/Chatroom.java
src/main/java/com/novelbot/api/service/auth/LoginService.java
src/main/java/com/novelbot/api/service/auth/UserDetailsService.java

JwtToken 생성, 디코딩 클래스 분리 작성
---
- JWT 발급 로직 추가
---
---
```bash
./gradlew clean build

[Fix] JwtToken 처리 로직 분리

---

src/main/java/com/novelbot/api/config/OpenApiConfig.java
src/main/java/com/novelbot/api/controller/AuthController.java
src/main/java/com/novelbot/api/controller/ChatController.java
src/main/java/com/novelbot/api/controller/EpisodeController.java
src/main/java/com/novelbot/api/controller/NovelController.java
src/main/java/com/novelbot/api/controller/PurchaseController.java
src/main/java/com/novelbot/api/controller/QueryController.java
src/main/java/com/novelbot/api/controller/ReadingProgressController.java
src/main/java/com/novelbot/api/controller/UserController.java
src/main/java/com/novelbot/api/service/chat/QueryService.java

- swagger-ui 추가
---
- API 명세서를 위한 swagger-ui 추가
---
---
```bash
close #

[Feat] swagger-ui 추가

---

src/main/java/com/novelbot/api/controller/ChatController.java
src/main/java/com/novelbot/api/controller/QueryController.java
src/main/java/com/novelbot/api/service/chat/ChatroomService.java
src/main/java/com/novelbot/api/service/chat/QueryService.java

- Post 계층에서 불필요하게 사용된 DTO 제거
---
- Controller와 Service 계층 수정
---
---
```bash
close #

[Refactor] Post 계층의 불필요한 DTO 제거

---

src/main/java/com/novelbot/api/config/OpenApiConfig.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] swagger basic url 추가

---

src/main/java/com/novelbot/api/service/novel/NovelService.java

- Search data가 없을 때 400 error -> 404 error
---
- NOT FOUND Error로 수정
---
---
```bash

[Fix] Search Error code 수정

---

src/main/java/com/novelbot/api/domain/Purchase.java
src/main/java/com/novelbot/api/domain/UserReadingProgress.java
src/main/java/com/novelbot/api/repository/PurchaseRepository.java
src/main/java/com/novelbot/api/repository/ReadingProgressRepository.java
src/main/java/com/novelbot/api/service/purchase/PurchaseService.java
src/main/java/com/novelbot/api/service/reading/ReadingProcessService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

readingprocessservice 작성, purchase 생성자까지 작성 완료,

---

build.gradle
src/main/java/com/novelbot/api/domain/UserReadingProgress.java
src/main/java/com/novelbot/api/repository/ReadingProgressRepository.java

- gradle build 시 제외시켰던 ChatRoom build 포함
---
- build.gradle
---
---
예:
```bash
#33

[Fix] gradlew build 시 chat add

---

src/main/java/com/novelbot/api/domain/UserReadingProgress.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] UserReadingProgress primary ID 추가

---

src/main/java/com/novelbot/api/repository/ReadingProgressRepository.java
src/main/java/com/novelbot/api/service/reading/ReadingProcessService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

readingprocess service, repository ã일부 수정

---

src/main/java/com/novelbot/api/config/WebConfig.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] CORS 정책 무시

---

src/main/java/com/novelbot/api/dto/purchase/PurchaseDto.java
src/main/java/com/novelbot/api/mapper/purchase/PurchaseDtoMapper.java
src/main/java/com/novelbot/api/repository/PurchaseRepository.java
src/main/java/com/novelbot/api/service/purchase/PurchaseService.java
src/main/java/com/novelbot/api/service/reading/ReadingProcessService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

purchase, readingprocess service 코드 수정

---

build.gradle

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] 실행 가능한 jar을 하나만 설정

---

src/main/java/com/novelbot/api/controller/EpisodeController.java
src/main/java/com/novelbot/api/controller/NovelController.java
src/main/java/com/novelbot/api/controller/PurchaseController.java
src/main/java/com/novelbot/api/controller/ReadingProgressController.java
src/main/java/com/novelbot/api/service/novel/EpisodeService.java
src/main/java/com/novelbot/api/service/novel/NovelService.java
src/main/java/com/novelbot/api/service/reading/ReadingProcessService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

novel, episode, purchase, reading process controller, service 코드 수정

---

src/main/java/com/novelbot/api/controller/AuthController.java
src/main/resources/application.properties

- logout 동작 오류 기능 수정
---
- authorize header 추가
---
---
예:
```bash
./graldw test
close #

[Fix] logout 기능 fix

---

src/main/java/com/novelbot/api/domain/Queries.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] LLM_id change Long from string

---

src/main/java/com/novelbot/api/config/JwtAuthenticationFilter.java
src/main/java/com/novelbot/api/config/OpenApiConfig.java
src/main/java/com/novelbot/api/config/SecurityConfig.java
src/main/java/com/novelbot/api/controller/AuthController.java
src/main/java/com/novelbot/api/controller/ChatController.java
src/main/java/com/novelbot/api/controller/PurchaseController.java
src/main/java/com/novelbot/api/controller/ReadingProgressController.java
src/main/java/com/novelbot/api/controller/UserController.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] Swagger를 위한 보안 설정 추가

---

build.gradle
src/main/java/com/novelbot/api/config/GCSConfig.java
src/main/java/com/novelbot/api/controller/NovelController.java
src/main/java/com/novelbot/api/service/GCS/GCSService.java
src/main/java/com/novelbot/api/service/novel/NovelService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

cover_image 활용 로직 제발 되거라

---

src/main/java/com/novelbot/api/service/chat/ChatroomService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] lazy loading 문제 해결

---

src/main/java/com/novelbot/api/service/purchase/PurchaseService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] Purchase 로직 수정

---

src/main/java/com/novelbot/api/dto/API/QueryAsk.java
src/main/java/com/novelbot/api/service/API/APIService.java
src/main/java/com/novelbot/api/test/AIServerTest.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] AI 서버 토큰 재발급 로직 추가

---

src/main/java/com/novelbot/api/service/chat/QueryService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] 비동기 처리가 아닌 멀티쓰레드 처리로 변경

---

src/main/java/com/novelbot/api/dto/API/QueryAsk.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] max_token 길이 2000으로 제한

---

src/main/java/com/novelbot/api/service/API/APIService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] AI 서버 로그인 시 에러 콘솔 추가

---

src/main/java/com/novelbot/api/service/chat/QueryService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] Websocket healthy check code 추가

---

src/main/java/com/novelbot/api/repository/PurchaseRepository.java
src/main/java/com/novelbot/api/service/chat/QueryService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] Hibernate lazy load 문제 해결

---

src/main/java/com/novelbot/api/service/API/APIService.java
src/main/java/com/novelbot/api/service/chat/QueryService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] Stream 데이터 처리 로직 수정

---

src/main/java/com/novelbot/api/service/chat/QueryService.java

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Fix] topic 불일치 해결"

---

README.md

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] ReadMe 추가

---

.gitignore
README.md
src/main/java/com/novelbot/api/config/GCSConfig.java
src/main/java/com/novelbot/api/domain/Chatroom.java
src/main/java/com/novelbot/api/domain/Episode.java
src/main/java/com/novelbot/api/domain/Queries.java
src/main/java/com/novelbot/api/domain/User.java
src/main/java/com/novelbot/api/domain/UserReadingProgress.java
src/main/java/com/novelbot/api/service/GCS/GCSService.java
src/main/java/com/novelbot/api/service/auth/LogoutService.java
src/main/resources/application-local.properties
src/main/resources/test-data.sql
websocket-test.html

---
예:
- JWT 발급 로직 추가
- 테스트 코드 5건 작성
---
---
예:
```bash
close #

[Feat] 로컬에서도 테스트 가능하도록 수정
